import img1 from '../assets/images/png/card-img.png'
import calenderImg from '../assets/images/svg/calender-svg.svg'
import locationImg from '../assets/images/svg/location-svg.svg'
import peopleImg from '../assets/images/svg/people-svg.svg'
export const CARD_DATA = [
    {
        CardImg: img1,
        CalenderImg: calenderImg,
        DateText: '10/02/2022',
        location: locationImg,
        LocationText: 'Mumbai',
        People: peopleImg,
        PeopleText: '1,080',
        CardText: 'Lorem ipsum dolar sit de',
    },
    {
        CardImg: img1,
        CalenderImg: calenderImg,
        DateText: '10/02/2022',
        location: locationImg,
        LocationText: 'Mumbai',
        People: peopleImg,
        PeopleText: '1,080',
        CardText: 'Lorem ipsum dolar sit de',
    },
    {
        CardImg: img1,
        CalenderImg: calenderImg,
        DateText: '10/02/2022',
        location: locationImg,
        LocationText: 'Mumbai',
        People: peopleImg,
        PeopleText: '1,080',
        CardText: 'Lorem ipsum dolar sit de',
    },
    {
        CardImg: img1,
        CalenderImg: calenderImg,
        DateText: '10/02/2022',
        location: locationImg,
        LocationText: 'Mumbai',
        People: peopleImg,
        PeopleText: '1,080',
        CardText: 'Lorem ipsum dolar sit de',
    },
    {
        CardImg: img1,
        CalenderImg: calenderImg,
        DateText: '10/02/2022',
        location: locationImg,
        LocationText: 'Mumbai',
        People: peopleImg,
        PeopleText: '1,080',
        CardText: 'Lorem ipsum dolar sit de',
    },
    {
        CardImg: img1,
        CalenderImg: calenderImg,
        DateText: '10/02/2022',
        location: locationImg,
        LocationText: 'Mumbai',
        People: peopleImg,
        PeopleText: '1,080',
        CardText: 'Lorem ipsum dolar sit de',
    },
    {
        CardImg: img1,
        CalenderImg: calenderImg,
        DateText: '10/02/2022',
        location: locationImg,
        LocationText: 'Mumbai',
        People: peopleImg,
        PeopleText: '1,080',
        CardText: 'Lorem ipsum dolar sit de',
    },
    {
        CardImg: img1,
        CalenderImg: calenderImg,
        DateText: '10/02/2022',
        location: locationImg,
        LocationText: 'Mumbai',
        People: peopleImg,
        PeopleText: '1,080',
        CardText: 'Lorem ipsum dolar sit de',
    },
    {
        CardImg: img1,
        CalenderImg: calenderImg,
        DateText: '10/02/2022',
        location: locationImg,
        LocationText: 'Mumbai',
        People: peopleImg,
        PeopleText: '1,080',
        CardText: 'Lorem ipsum dolar sit de',
    },
]